apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustup-io-monolith-cron
  labels:
    tier: backend
    layer: cron
  annotations:
    configmap.reloader.stakater.com/reload: "trustup-io-monolith"
    secret.reloader.stakater.com/reload: "trustup-io-monolith"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: cron
  template:
    metadata:
      labels:
        tier: backend
        layer: cron
    spec:
      containers:
        - name: cron
          image: henrotaym/trustup-io-monolith-cron:0.0.1
          envFrom:
            - configMapRef:
                name: trustup-io-monolith
            - secretRef:
                name: trustup-io-monolith