apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustup-io-trustup-pro-mock-cron
  labels:
    tier: backend
    layer: cron
  annotations:
    configmap.reloader.stakater.com/reload: "trustup-io-trustup-pro-mock"
    secret.reloader.stakater.com/reload: "trustup-io-trustup-pro-mock"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: cron
  template:
    metadata:
      labels:
        tier: backend
        layer: cron
    spec:
      containers:
        - name: cron
          image: henrotaym/trustup-io-trustup-pro-mock-cron:0.0.1
          envFrom:
            - configMapRef:
                name: trustup-io-trustup-pro-mock
            - secretRef:
                name: trustup-io-trustup-pro-mock